version: "3.3"
services:
  app:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ${CV_ROOT}:/app/static/files/cv
      - ${LETTER_ROOT}:/app/static/files/letter
      - ${STYLES_ROOT}:/app/static/files/styles
      - ./src:/app/src
      - ./static:/app/static
      - ./vite.config.ts:/app/vite.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./svelte.config.js:/app/svelte.config.js
    command: npm run dev -- --host 0.0.0.0